pool:
  vmImage: 'ubuntu-16.04'
steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
  - script: cargo install wasm-pack
    displayName: Install wasm-pack
  - script: npm ci
    displayName: Npm Install
  - script: './assets/build-wasm.sh'
    displayName: Build rust crate
  - script: 'wasm-pack test --node'
    workingDirectory: './crate'
    displayName: Test rust crate
  - script: npm run type-check
    displayName: Typescript check
  - script: npm run unit
    displayName: Unit Tests
  - script: npm test
    displayName: e2e tests
  - script: docker build .
    displayName: build docker image
  - script: ./assets/wasm-size-check.sh
    displayName: test wasm bundle size
